### Variable para la URL base
@api = http://localhost:3000/api/transactions

### 1. PROBAR RUTA INICIAL (BASE)
GET http://localhost:3000/

###

### 2. CREAR UN INGRESO (Salario)
POST {{api}}
Content-Type: application/json

{
    "type": "income",
    "amount": 1200000,
    "category": "Salario",
    "description": "Pago mensual proyecto SENA"
}

###

### 3. CREAR UN GASTO (Comida)
POST {{api}}
Content-Type: application/json

{
    "type": "expense",
    "amount": 85000,
    "category": "Comida",
    "description": "Supermercado semana"
}

###

### 4. OBTENER RESUMEN FINANCIERO (Dashboard)
GET {{api}}/summary

###

### 5. OBTENER GASTOS POR CATEGORÍA (Gráfica Circular)
GET {{api}}/stats/categories

###

### 6. OBTENER INSIGHTS (Comparativa Mes Anterior vs Actual)
GET {{api}}/stats/insights

###

### 7. OBTENER HISTORIAL CON PAGINACIÓN (Página 1, Límite 5)
GET {{api}}?page=1&limit=5

###

### 8. FILTRAR POR RANGO DE FECHAS
GET {{api}}?startDate=2026-04-01&endDate=2026-04-30

###

### 9. ACTUALIZAR UNA TRANSACCIÓN (PUT)
# Reemplaza el ID por uno real de tu base de datos
PUT {{api}}/REEMPLAZA_CON_UN_ID
Content-Type: application/json

{
    "amount": 90000,
    "description": "Supermercado (Precio actualizado)",
    "category": "Comida"
}

###

### 10. ELIMINAR UNA TRANSACCIÓN
DELETE {{api}}/REEMPLAZA_CON_UN_ID

###

### 11. PROBAR VALIDACIÓN (Error por monto negativo)
POST {{api}}
Content-Type: application/json

{
    "type": "expense",
    "amount": -500,
    "category": "Error",
    "description": "No debe guardarse"
}

###

### 12. PROBAR RUTA NO EXISTENTE
GET http://localhost:3000/api/ruta-falsa